In [1]:
import pandas as pd

In [3]:
data = "data.csv"
# Read the data into a DataFrame
df = pd.read_csv(data)
df = df[df['country'].str.contains('United States', na=False)]
# Display the filtered DataFrame
print(df)

      Unnamed: 0                 region_group           income_group  \
0         122984  Europe and Northern America  High income countries
1         122985  Europe and Northern America  High income countries
2         122986  Europe and Northern America  High income countries
3         122987  Europe and Northern America  High income countries
4         122988  Europe and Northern America  High income countries
...          ...                          ...                    ...
1140      212829  Europe and Northern America  High income countries
1141      212830  Europe and Northern America  High income countries
1142      212831  Europe and Northern America  High income countries
1143      212857  Europe and Northern America  High income countries
1144      212858  Europe and Northern America  High income countries

            country                                     category Location  \
0     United States                                 Sex & Wealth      NaN
1     United States                                 Sex & Wealth      NaN
2     United States                                 Sex & Wealth      NaN
3     United States                                 Sex & Wealth      NaN
4     United States                                 Sex & Wealth      NaN
...             ...                                          ...      ...
1140  United States  Location & Speaks Language at Home & Wealth    Rural
1141  United States  Location & Speaks Language at Home & Wealth    Rural
1142  United States  Location & Speaks Language at Home & Wealth    Rural
1143  United States                      Sex & Location & Wealth    Rural
1144  United States                      Sex & Location & Wealth    Rural

          Wealth  Region  Ethnicity  comp_prim_v2_m  ...  edu0_prim_m  \
0     Quintile 1     NaN        NaN          0.9798  ...          0.0
1     Quintile 2     NaN        NaN          1.0000  ...          0.0
2     Quintile 3     NaN        NaN          0.9983  ...          0.0
3     Quintile 4     NaN        NaN          0.9946  ...          0.0
4     Quintile 5     NaN        NaN          1.0000  ...          0.0
...          ...     ...        ...             ...  ...          ...
1140  Quintile 3     NaN        NaN          0.0000  ...          0.0
1141  Quintile 4     NaN        NaN          0.0000  ...          0.0
1142  Quintile 5     NaN        NaN          0.0000  ...          0.0
1143  Quintile 1     NaN        NaN          0.0000  ...          0.0
1144  Quintile 3     NaN        NaN          0.0000  ...          0.0

      edu0_prim_no  comp_higher_2yrs_2529_m  comp_higher_2yrs_2529_no  \
0              0.0                      0.0                       0.0
1              0.0                      0.0                       0.0
2              0.0                      0.0                       0.0
3              0.0                      0.0                       0.0
4              0.0                      0.0                       0.0
...            ...                      ...                       ...
1140           0.0                      0.0                       0.0
1141           0.0                      0.0                       0.0
1142           0.0                      0.0                       0.0
1143           0.0                      0.0                       0.0
1144           0.0                      0.0                       0.0

      comp_higher_4yrs_2529_m  comp_higher_4yrs_2529_no  \
0                         0.0                       0.0
1                         0.0                       0.0
2                         0.0                       0.0
3                         0.0                       0.0
4                         0.0                       0.0
...                       ...                       ...
1140                      0.0                       0.0
1141                      0.0                       0.0
1142                      0.0                       0.0
1143                      0.0                       0.0
1144                      0.0                       0.0

      comp_higher_4yrs_3034_m  comp_higher_4yrs_3034_no  attend_higher_1822_m  \
0                         0.0                       0.0                   0.0
1                         0.0                       0.0                   0.0
2                         0.0                       0.0                   0.0
3                         0.0                       0.0                   0.0
4                         0.0                       0.0                   0.0
...                       ...                       ...                   ...
1140                      0.0                       0.0                   0.0
1141                      0.0                       0.0                   0.0
1142                      0.0                       0.0                   0.0
1143                      0.0                       0.0                   0.0
1144                      0.0                       0.0                   0.0

      attend_higher_1822_no
0                       0.0
1                       0.0
2                       0.0
3                       0.0
4                       0.0
...                     ...
1140                    0.0
1141                    0.0
1142                    0.0
1143                    0.0
1144                    0.0

[1145 rows x 47 columns]

In [4]:
print(df.columns)

Index(['Unnamed: 0', 'region_group', 'income_group', 'country', 'category',
       'Location', 'Wealth', 'Region', 'Ethnicity', 'comp_prim_v2_m',
       'comp_lowsec_v2_m', 'comp_upsec_v2_m', 'comp_prim_1524_m',
       'comp_lowsec_1524_m', 'comp_upsec_2029_m', 'eduyears_2024_m',
       'edu2_2024_m', 'edu4_2024_m', 'eduout_prim_m', 'eduout_lowsec_m',
       'eduout_upsec_m', 'comp_prim_v2_no', 'comp_lowsec_v2_no',
       'comp_upsec_v2_no', 'comp_prim_1524_no', 'comp_lowsec_1524_no',
       'comp_upsec_2029_no', 'eduyears_2024_no', 'edu2_2024_no',
       'edu4_2024_no', 'eduout_prim_no', 'eduout_lowsec_no', 'eduout_upsec_no',
       'preschool_3_m', 'preschool_3_no', 'preschool_1ybefore_m',
       'preschool_1ybefore_no', 'edu0_prim_m', 'edu0_prim_no',
       'comp_higher_2yrs_2529_m', 'comp_higher_2yrs_2529_no',
       'comp_higher_4yrs_2529_m', 'comp_higher_4yrs_2529_no',
       'comp_higher_4yrs_3034_m', 'comp_higher_4yrs_3034_no',
       'attend_higher_1822_m', 'attend_higher_1822_no'],
      dtype='object')

In [5]:
columns_to_keep = [
    'region_group', 'income_group', 'country', 'category', 'Location', 'Wealth', 'Region',
    'Ethnicity','comp_prim_v2_m',
    'comp_lowsec_v2_m', 'comp_upsec_v2_m', 'comp_prim_1524_m',
    'comp_lowsec_1524_m', 'comp_upsec_2029_m', 'eduyears_2024_m',
    'edu2_2024_m', 'edu4_2024_m', 'eduout_prim_m', 'eduout_lowsec_m',
    'eduout_upsec_m', 'comp_prim_v2_no', 'comp_lowsec_v2_no',
    'comp_upsec_v2_no', 'comp_prim_1524_no', 'comp_lowsec_1524_no',
    'comp_upsec_2029_no', 'eduyears_2024_no', 'edu2_2024_no',
    'edu4_2024_no', 'eduout_prim_no', 'eduout_lowsec_no', 'eduout_upsec_no',
    'preschool_3_m', 'preschool_3_no', 'preschool_1ybefore_m',
    'preschool_1ybefore_no', 'edu0_prim_m', 'edu0_prim_no', 
    'comp_higher_2yrs_2529_m', 'comp_higher_2yrs_2529_no',
    'comp_higher_4yrs_2529_m', 'comp_higher_4yrs_2529_no',
    'comp_higher_4yrs_3034_m', 'comp_higher_4yrs_3034_no',
    'attend_higher_1822_m', 'attend_higher_1822_no'
]
df = df[columns_to_keep]

In [6]:
df = df[df['Wealth'].notna()]

# Display the filtered DataFrame
print(df)

                     region_group           income_group        country  \
0     Europe and Northern America  High income countries  United States
1     Europe and Northern America  High income countries  United States
2     Europe and Northern America  High income countries  United States
3     Europe and Northern America  High income countries  United States
4     Europe and Northern America  High income countries  United States
...                           ...                    ...            ...
1140  Europe and Northern America  High income countries  United States
1141  Europe and Northern America  High income countries  United States
1142  Europe and Northern America  High income countries  United States
1143  Europe and Northern America  High income countries  United States
1144  Europe and Northern America  High income countries  United States

                                         category Location      Wealth  \
0                                    Sex & Wealth      NaN  Quintile 1
1                                    Sex & Wealth      NaN  Quintile 2
2                                    Sex & Wealth      NaN  Quintile 3
3                                    Sex & Wealth      NaN  Quintile 4
4                                    Sex & Wealth      NaN  Quintile 5
...                                           ...      ...         ...
1140  Location & Speaks Language at Home & Wealth    Rural  Quintile 3
1141  Location & Speaks Language at Home & Wealth    Rural  Quintile 4
1142  Location & Speaks Language at Home & Wealth    Rural  Quintile 5
1143                      Sex & Location & Wealth    Rural  Quintile 1
1144                      Sex & Location & Wealth    Rural  Quintile 3

      Region  Ethnicity  comp_prim_v2_m  comp_lowsec_v2_m  ...  edu0_prim_m  \
0        NaN        NaN          0.9798            0.9783  ...          0.0
1        NaN        NaN          1.0000            0.9871  ...          0.0
2        NaN        NaN          0.9983            0.9850  ...          0.0
3        NaN        NaN          0.9946            0.9908  ...          0.0
4        NaN        NaN          1.0000            0.9950  ...          0.0
...      ...        ...             ...               ...  ...          ...
1140     NaN        NaN          0.0000            0.0000  ...          0.0
1141     NaN        NaN          0.0000            0.0000  ...          0.0
1142     NaN        NaN          0.0000            0.0000  ...          0.0
1143     NaN        NaN          0.0000            0.0000  ...          0.0
1144     NaN        NaN          0.0000            0.0000  ...          0.0

      edu0_prim_no  comp_higher_2yrs_2529_m  comp_higher_2yrs_2529_no  \
0              0.0                      0.0                       0.0
1              0.0                      0.0                       0.0
2              0.0                      0.0                       0.0
3              0.0                      0.0                       0.0
4              0.0                      0.0                       0.0
...            ...                      ...                       ...
1140           0.0                      0.0                       0.0
1141           0.0                      0.0                       0.0
1142           0.0                      0.0                       0.0
1143           0.0                      0.0                       0.0
1144           0.0                      0.0                       0.0

      comp_higher_4yrs_2529_m  comp_higher_4yrs_2529_no  \
0                         0.0                       0.0
1                         0.0                       0.0
2                         0.0                       0.0
3                         0.0                       0.0
4                         0.0                       0.0
...                       ...                       ...
1140                      0.0                       0.0
1141                      0.0                       0.0
1142                      0.0                       0.0
1143                      0.0                       0.0
1144                      0.0                       0.0

      comp_higher_4yrs_3034_m  comp_higher_4yrs_3034_no  attend_higher_1822_m  \
0                         0.0                       0.0                   0.0
1                         0.0                       0.0                   0.0
2                         0.0                       0.0                   0.0
3                         0.0                       0.0                   0.0
4                         0.0                       0.0                   0.0
...                       ...                       ...                   ...
1140                      0.0                       0.0                   0.0
1141                      0.0                       0.0                   0.0
1142                      0.0                       0.0                   0.0
1143                      0.0                       0.0                   0.0
1144                      0.0                       0.0                   0.0

      attend_higher_1822_no
0                       0.0
1                       0.0
2                       0.0
3                       0.0
4                       0.0
...                     ...
1140                    0.0
1141                    0.0
1142                    0.0
1143                    0.0
1144                    0.0

[1145 rows x 46 columns]

In [7]:
def fill_missing_values(column):
    if pd.api.types.is_numeric_dtype(column):
        return column.fillna(0)
    else:
        return column.fillna('None')

# Apply the function to each column in the DataFrame
df = df.apply(fill_missing_values)

# Display the DataFrame with filled missing values
print(df)

                     region_group           income_group        country  \
0     Europe and Northern America  High income countries  United States
1     Europe and Northern America  High income countries  United States
2     Europe and Northern America  High income countries  United States
3     Europe and Northern America  High income countries  United States
4     Europe and Northern America  High income countries  United States
...                           ...                    ...            ...
1140  Europe and Northern America  High income countries  United States
1141  Europe and Northern America  High income countries  United States
1142  Europe and Northern America  High income countries  United States
1143  Europe and Northern America  High income countries  United States
1144  Europe and Northern America  High income countries  United States

                                         category Location      Wealth  \
0                                    Sex & Wealth     None  Quintile 1
1                                    Sex & Wealth     None  Quintile 2
2                                    Sex & Wealth     None  Quintile 3
3                                    Sex & Wealth     None  Quintile 4
4                                    Sex & Wealth     None  Quintile 5
...                                           ...      ...         ...
1140  Location & Speaks Language at Home & Wealth    Rural  Quintile 3
1141  Location & Speaks Language at Home & Wealth    Rural  Quintile 4
1142  Location & Speaks Language at Home & Wealth    Rural  Quintile 5
1143                      Sex & Location & Wealth    Rural  Quintile 1
1144                      Sex & Location & Wealth    Rural  Quintile 3

      Region  Ethnicity  comp_prim_v2_m  comp_lowsec_v2_m  ...  edu0_prim_m  \
0        0.0        0.0          0.9798            0.9783  ...          0.0
1        0.0        0.0          1.0000            0.9871  ...          0.0
2        0.0        0.0          0.9983            0.9850  ...          0.0
3        0.0        0.0          0.9946            0.9908  ...          0.0
4        0.0        0.0          1.0000            0.9950  ...          0.0
...      ...        ...             ...               ...  ...          ...
1140     0.0        0.0          0.0000            0.0000  ...          0.0
1141     0.0        0.0          0.0000            0.0000  ...          0.0
1142     0.0        0.0          0.0000            0.0000  ...          0.0
1143     0.0        0.0          0.0000            0.0000  ...          0.0
1144     0.0        0.0          0.0000            0.0000  ...          0.0

      edu0_prim_no  comp_higher_2yrs_2529_m  comp_higher_2yrs_2529_no  \
0              0.0                      0.0                       0.0
1              0.0                      0.0                       0.0
2              0.0                      0.0                       0.0
3              0.0                      0.0                       0.0
4              0.0                      0.0                       0.0
...            ...                      ...                       ...
1140           0.0                      0.0                       0.0
1141           0.0                      0.0                       0.0
1142           0.0                      0.0                       0.0
1143           0.0                      0.0                       0.0
1144           0.0                      0.0                       0.0

      comp_higher_4yrs_2529_m  comp_higher_4yrs_2529_no  \
0                         0.0                       0.0
1                         0.0                       0.0
2                         0.0                       0.0
3                         0.0                       0.0
4                         0.0                       0.0
...                       ...                       ...
1140                      0.0                       0.0
1141                      0.0                       0.0
1142                      0.0                       0.0
1143                      0.0                       0.0
1144                      0.0                       0.0

      comp_higher_4yrs_3034_m  comp_higher_4yrs_3034_no  attend_higher_1822_m  \
0                         0.0                       0.0                   0.0
1                         0.0                       0.0                   0.0
2                         0.0                       0.0                   0.0
3                         0.0                       0.0                   0.0
4                         0.0                       0.0                   0.0
...                       ...                       ...                   ...
1140                      0.0                       0.0                   0.0
1141                      0.0                       0.0                   0.0
1142                      0.0                       0.0                   0.0
1143                      0.0                       0.0                   0.0
1144                      0.0                       0.0                   0.0

      attend_higher_1822_no
0                       0.0
1                       0.0
2                       0.0
3                       0.0
4                       0.0
...                     ...
1140                    0.0
1141                    0.0
1142                    0.0
1143                    0.0
1144                    0.0

[1145 rows x 46 columns]

In [8]:
df.to_csv('cleaned_data.csv')